#pragma once

#include "sdkconfig.h"

#define AGORA_DEMO_APP_ID        CONFIG_AGORA_DEMO_APP_ID
#define AGORA_DEMO_APP_CERT      CONFIG_AGORA_DEMO_APP_CERT
#define AGORA_DEMO_WHIP_BASE_URL CONFIG_AGORA_DEMO_WHIP_BASE_URL
#define AGORA_DEMO_BOT_STATION_BASE_URL \
    CONFIG_AGORA_DEMO_BOT_STATION_BASE_URL
#define AGORA_DEMO_HARDWARE_MODEL CONFIG_AGORA_DEMO_HARDWARE_MODEL
#define AGORA_DEMO_WIFI_SSID     CONFIG_AGORA_DEMO_WIFI_SSID
#define AGORA_DEMO_WIFI_PASSWORD CONFIG_AGORA_DEMO_WIFI_PASSWORD

#define AGORA_DEMO_AUDIO_SAMPLE_RATE   48000
#define AGORA_DEMO_AUDIO_CHANNELS      1
#define AGORA_DEMO_TOKEN_TTL_SECONDS   600
#define AGORA_DEMO_URL_SIZE            512
#define AGORA_DEMO_TOKEN_SIZE          1536
#define AGORA_DEMO_CHANNEL_SIZE        128
#define AGORA_DEMO_UID_SIZE            65
#define AGORA_DEMO_MIN_VALID_UNIX_TIME 1704067200
